version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mini-hub-fastapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ojs85guib22w"
s3_prefix = "mini-hub-fastapi"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
